name: Build Android Debug APK

on:
  # Allow manual run from the Actions tab
  workflow_dispatch:

  # Also run automatically when you push to main branch
  push:
    branches: [ main ]

jobs:
  build:
    name: Build Debug APK
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout your code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up Java environment
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3️⃣ Cache Gradle files to speed up builds
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle

      # 4️⃣ Make Gradlew executable (important for Linux)
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 5️⃣ Build the Debug APK
      - name: Build Debug APK
        run: ./gradlew assembleDebug --no-daemon

      # 6️⃣ Upload APK as an artifact
      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: android-debug-apk
          path: app/build/outputs/apk/debug/*.apk
